CREATE TABLE public."Departments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Address" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Departments"
    OWNER to "user";


CREATE TABLE public."Employees"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "MiddleName" text COLLATE pg_catalog."default" NOT NULL,
    "LastName" text COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" text COLLATE pg_catalog."default" NOT NULL,
    "EmailAddress" text COLLATE pg_catalog."default" NOT NULL,
    "DepartmentId" integer NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT fk_department FOREIGN KEY ("DepartmentId")
        REFERENCES public."Departments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Employees"
    OWNER to "user";
	
	
CREATE TABLE public."Tasks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "Responsible" integer NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
    CONSTRAINT fk_employee FOREIGN KEY ("Responsible")
        REFERENCES public."Employees" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Tasks"
    OWNER to "user";


CREATE TABLE public."Clients"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "MiddleName" text COLLATE pg_catalog."default" NOT NULL,
    "LastName" text COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" text COLLATE pg_catalog."default" NOT NULL,
    "EmailAddress" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Clients"
    OWNER to "user";


CREATE TABLE public."Applications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "ClientId" integer NOT NULL,
    "TaskId" integer NOT NULL,
    CONSTRAINT "PK_Applications" PRIMARY KEY ("Id"),
    CONSTRAINT fk_client FOREIGN KEY ("ClientId")
        REFERENCES public."Clients" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_task FOREIGN KEY ("TaskId")
        REFERENCES public."Tasks" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public."Applications"
    OWNER to "user";
	
	
